name: Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Deploy to Staging
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        WP_PATH: ${{ vars.WP_PATH_DEV }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem -p $SSH_PORT $SSH_USER@$SSH_HOST '
          echo "WP_PATH: $WP_PATH" &&
          pwd &&
          ls -la &&
          cat estaemdev.txt &&
          cd $WP_PATH &&
          git pull origin develop &&

          # Sync Plugins
          wp plugin list --field=name --allow-root > installed_plugins.txt &&
          jq -c ".[]" .github/workflows/plugins.json > plugins_to_sync