name: Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug environment
      run: |
        php -v
        which php
        echo $PATH

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Deploy to Staging
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        WP_PATH: ${{ vars.WP_DEV_DIR_FROM_HOME }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem -p $SSH_PORT $SSH_USER@$SSH_HOST '
          echo "WP_PATH: $WP_PATH" &&
          pwd &&
          ls -la &&
          cd "$WP_PATH" &&
          cat estaemdev.txt &&
          git pull origin develop &&

          # Sync Plugins
          wp plugin list --field=name --allow-root > installed_plugins.txt &&
          grep -oP '"'"'name'": "\K[^"]+'"' .github/workflows/plugins.json > plugins_to_sync.txt &&
          while IFS= read -r plugin; do
            name=$(echo "$plugin" | awk -F'"'"'\"'\"' '{print $4}')
            status=$(grep -A 3 "\"name\": \"$name\"" .github/workflows/plugins.json | grep -oP '"'"'status'": "\K[^"]+'"' )
            version=$(grep -A 3 "\"name\": \"$name\"" .github/workflows/plugins.json | grep -oP '"'"'version'": "\K[^"]+'"' )
            if ! grep -q "$name" installed_plugins.txt; then
              wp plugin install "$name" --version="$version" --allow-root
            else
              wp plugin update "$name" --version="$version" --allow-root
            fi
            if [ "$status" = "active" ]; then
              wp plugin activate "$name" --allow-root
            else
              wp plugin deactivate "$name" --allow-root
            fi
          done < plugins_to_sync.txt &&
          for installed_plugin in $(cat installed_plugins.txt); do
            if ! grep -q "\"name\": \"$installed_plugin\"" .github/workflows/plugins.json; then
              wp plugin delete "$installed_plugin" --allow-root
            fi
          done &&

          # Sync Themes
          wp theme list --field=name --allow-root > installed_themes.txt &&
          grep -oP '"'"'name'": "\K[^"]+'"' .github/workflows/themes.json > themes_to_sync.txt &&
          while IFS= read -r theme; do
            name=$(echo "$theme" | awk -F'"'"'\"'\"' '{print $4}')
            status=$(grep -A 3 "\"name\": \"$name\"" .github/workflows/themes.json | grep -oP '"'"'status'": "\K[^"]+'"' )
            version=$(grep -A 3 "\"name\": \"$name\"" .github/workflows/themes.json | grep -oP '"'"'version'": "\K[^"]+'"' )
            update_version=$(grep -A 3 "\"name\": \"$name\"" .github/workflows/themes.json | grep -oP '"'"'update_version'": "\K[^"]+'"' )
            if ! grep -q "$name" installed_themes.txt; then
              wp theme install "$name" --version="$version" --allow-root
            else
              wp theme update "$name" --version="$update_version" --allow-root
            fi
            if [ "$status" = "active" ]; then
              wp theme activate "$name" --allow-root
            fi
          done < themes_to_sync.txt &&
          for installed_theme in $(cat installed_themes.txt); do
            if ! grep -q "\"name\": \"$installed_theme\"" .github/workflows/themes.json; then
              wp theme delete "$installed_theme" --allow-root
            fi
          done
        '
        rm private_key.pem